# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Covid_19(object):
    def setupUi(self, Covid_19):
        Covid_19.setObjectName("Covid_19")
        Covid_19.resize(562, 297)
        Covid_19.setStyleSheet("background: #363636; color: #c71d22;")
        self.centralwidget = QtWidgets.QWidget(Covid_19)
        self.centralwidget.setObjectName("centralwidget")
        self.Cep = QtWidgets.QLineEdit(self.centralwidget)
        self.Cep.setGeometry(QtCore.QRect(150, 20, 271, 30))
        self.Cep.setAutoFillBackground(False)
        self.Cep.setStyleSheet("font: red; background: #3a5990; border-radius: 10px;")
        self.Cep.setObjectName("Cep")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 70, 91, 30))
        self.pushButton.setStyleSheet("background: #3a5990; border-radius: 10px;")
        self.pushButton.setObjectName("pushButton")
        self.CEP = QtWidgets.QLabel(self.centralwidget)
        self.CEP.setGeometry(QtCore.QRect(19, 136, 281, 22))
        self.CEP.setObjectName("CEP")
        self.lgd = QtWidgets.QLabel(self.centralwidget)
        self.lgd.setGeometry(QtCore.QRect(19, 166, 281, 22))
        self.lgd.setObjectName("lgd")
        self.cpl = QtWidgets.QLabel(self.centralwidget)
        self.cpl.setGeometry(QtCore.QRect(19, 196, 281, 22))
        self.cpl.setObjectName("cpl")
        self.uf = QtWidgets.QLabel(self.centralwidget)
        self.uf.setGeometry(QtCore.QRect(320, 166, 231, 22))
        self.uf.setObjectName("uf")
        self.bairro = QtWidgets.QLabel(self.centralwidget)
        self.bairro.setGeometry(QtCore.QRect(19, 226, 281, 22))
        self.bairro.setObjectName("bairro")
        self.ddd = QtWidgets.QLabel(self.centralwidget)
        self.ddd.setGeometry(QtCore.QRect(319, 226, 241, 22))
        self.ddd.setStyleSheet("")
        self.ddd.setObjectName("ddd")
        self.ibge = QtWidgets.QLabel(self.centralwidget)
        self.ibge.setGeometry(QtCore.QRect(320, 196, 231, 22))
        self.ibge.setObjectName("ibge")
        self.gia = QtWidgets.QLabel(self.centralwidget)
        self.gia.setGeometry(QtCore.QRect(20, 256, 281, 22))
        self.gia.setObjectName("gia")
        self.local = QtWidgets.QLabel(self.centralwidget)
        self.local.setGeometry(QtCore.QRect(320, 136, 231, 22))
        self.local.setObjectName("local")
        self.Help = QtWidgets.QPushButton(self.centralwidget)
        self.Help.setGeometry(QtCore.QRect(470, 0, 91, 30))
        self.Help.setObjectName("Help")
        Covid_19.setCentralWidget(self.centralwidget)

        self.retranslateUi(Covid_19)
        QtCore.QMetaObject.connectSlotsByName(Covid_19)

    def retranslateUi(self, Covid_19):
        _translate = QtCore.QCoreApplication.translate
        Covid_19.setWindowTitle(_translate("Covid_19", "CEP"))
        self.pushButton.setText(_translate("Covid_19", "Pesquisar"))
        self.CEP.setText(_translate("Covid_19", "CEP: ??"))
        self.lgd.setText(_translate("Covid_19", "Logradura: ??"))
        self.cpl.setText(_translate("Covid_19", "Complemento: ??"))
        self.uf.setText(_translate("Covid_19", "Bairro: ??"))
        self.bairro.setText(_translate("Covid_19", "Localidade: ??"))
        self.ddd.setText(_translate("Covid_19", "uf: ??"))
        self.ibge.setText(_translate("Covid_19", "Ibge: ??"))
        self.gia.setText(_translate("Covid_19", "Gia: ??"))
        self.local.setText(_translate("Covid_19", "DDD: ??"))
        self.Help.setText(_translate("Covid_19", "Ajuda"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Covid_19 = QtWidgets.QMainWindow()
    ui = Ui_Covid_19()
    ui.setupUi(Covid_19)
    Covid_19.show()
    sys.exit(app.exec_())
